### ISSUE TITLE
enter when inputting username does nothing

### ISSUE THREAD

**Issue by MinIsMin** [w3yden/ultrascreen#1]
### Steps to reproduce:
- Open UltraScreen
- Enter a username
- Press Enter

### What should happen:
You should get logged in

### What actually happened:
Nothing

### More info:
It's faster with enter especially since the username is not saved

**Comment by w3yden** [comment]
I guess this could have been PeerJS connection problem like in #7.
If you are still interested in this prioject and have a problem you can open a new issue
