### ISSUE TITLE
No ID given after Login (openSUSE 15.1)

### ISSUE THREAD

**Issue by ReinerText** [w3yden/ultrascreen#7]
When I login I only have a hyphen as a Ultrascreen ID. That happens on two openSUSE 15.1 hosts.

**Comment by Dobrowit** [comment]
I checked on two different computers with Windows 10 Pro. The ID is not shown either.

**Comment by tiotrom** [comment]
Same here on Manjaro...is this still developed? Thanks

**Comment by w3yden** [comment]
Maybe the PeerJS broker was down. You can check its status [here](https://stats.uptimerobot.com/B7Ww3sDBVz), in case it is still relevant for you.
